// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamStatistics.Data;

#nullable disable

namespace TeamStatistics.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230412022600_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TeamStatistics.Data.Entities.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IssueStatuses");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Open"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ready for Release"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ready for Test"
                        },
                        new
                        {
                            Id = 5,
                            Name = "In Test"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Done"
                        },
                        new
                        {
                            Id = 2,
                            Name = "To Do"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
